services:
  - type: web
    name: ethara-ai
    runtime: python
    pythonVersion: "3.11.10"
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 127.0.0.1 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: MONGODB_URL
        value: MONGODB_URL=mongodb+srv://jodd0110_db_user:12345@cluster0.l2utpy5.mongodb.net/hrms_lite?retryWrites=true&w=majority&tls=true
      - key: DATABASE_NAME
        value: hrms_lite
      - key: CORS_ORIGINS
        value: http://localhost:3000,https://your-frontend.vercel.app